import nodemailer from "nodemailer";
import { NextResponse } from "next/server";
import dbConnect from "@/lib/dbConnect";
import Donation from "@/models/Donation"; // Import the Donation model

// Initialize Zoho Mail transporter
// const transporter = nodemailer.createTransport({
//   host: process.env.ZOHO_MAIL_HOST,
//   port: parseInt(process.env.ZOHO_MAIL_PORT),
//   secure: process.env.ZOHO_MAIL_SECURE === "true",
//   auth: {
//     user: process.env.GMAIL_USER}>`, // Use GMAIL_USER for donor email,
//     pass: process.env.ZOHO_MAIL_PASSWORD,
//   },
// });

const transporter = nodemailer.createTransport({
  service: "gmail",
  auth: {
    user: process.env.GMAIL_USER,
    pass: process.env.GMAIL_PASSWORD,
  },
});

export async function POST(request) {
  try {
    const donationData = await request.json();

    // Connect to database
    await dbConnect();

    // Store donation in database
    const newDonation = new Donation({
      ...donationData,
      donationDate: new Date(),
    });
    const savedDonation = await newDonation.save();

    // Email to donor
    const donorMailOptions = {
      from: `ATMA Donations <${process.env.GMAIL_USER}>`, // Use GMAIL_USER for donor email
      to: donationData.email,
      subject: "Thank you for your donation to ATMA",
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h1 style="color: #1a365d;">Thank you for your support, ${
            donationData.firstName
          }!</h1>
          
          <div style="background-color: #f7fafc; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <h2 style="color: #2d3748;">Donation Details</h2>
            <p><strong>Amount:</strong> $${donationData.amount}</p>
            <p><strong>Transaction ID:</strong> ${
              donationData.transactionId
            }</p>
            <p><strong>Date:</strong> ${new Date().toLocaleDateString()}</p>
          </div>
          
          <div style="background-color: #ebf8ff; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <h2 style="color: #2b6cb0;">Tax Deduction Information</h2>
            <p>ATMA is a 501(c)(3) nonprofit organization.</p>
            <p>No goods or services were provided in exchange for this contribution.</p>
            <p>This email serves as your receipt for tax purposes.</p>
          </div>
          
          <div style="margin: 20px 0;">
            <a href="${process.env.NEXT_PUBLIC_SITE_URL}" 
               style="display: inline-block; background-color: #4299e1; color: white; 
                      padding: 10px 20px; text-decoration: none; border-radius: 4px;
                      font-weight: bold;">
              Visit Our Website
            </a>
          </div>
          
          <div style="border-top: 1px solid #e2e8f0; padding-top: 20px; font-size: 0.9em; color: #718096;">
            <p>If you have any questions, please contact us at <a href="mailto:Atmausapresident@gmail.com" style="color: #3182ce;">Atmausapresident@gmail.com</a></p>
            <p>© ${new Date().getFullYear()} American Tamil Medical Association. All rights reserved.</p>
          </div>
        </div>
      `,
    };

    // Email to ATMA admin
    const adminMailOptions = {
      from: `ATMA Donations <${process.env.GMAIL_USER}>`, // Use GMAIL_USER for donor email
      to: "Atmausapresident@gmail.com",
      subject: `New Donation Received - $${donationData.amount}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h1 style="color: #1a365d;">New Donation Received</h1>
          
          <div style="background-color: #f7fafc; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <h2 style="color: #2d3748;">Donation Details</h2>
            <p><strong>Donor:</strong> ${donationData.firstName} ${
        donationData.lastName
      }</p>
            <p><strong>Email:</strong> ${donationData.email}</p>
            <p><strong>Amount:</strong> $${donationData.amount}</p>
            ${
              donationData.isRecurring
                ? `<p><strong>Recurring:</strong> ${donationData.recurringFrequency}</p>`
                : ""
            }
            <p><strong>Transaction ID:</strong> ${
              donationData.transactionId
            }</p>
            <p><strong>Date:</strong> ${new Date().toLocaleDateString()}</p>
          </div>
          
          <div style="border-top: 1px solid #e2e8f0; padding-top: 20px; font-size: 0.9em; color: #718096;">
            <p>This email was automatically generated by the ATMA donation system.</p>
          </div>
        </div>
      `,
    };

    // Send both emails
    await transporter.sendMail(donorMailOptions);
    await transporter.sendMail(adminMailOptions);

    return NextResponse.json(
      { success: true, donationId: savedDonation._id },
      { status: 201 }
    );
  } catch (error) {
    console.error("Donation processing error:", error);
    return NextResponse.json(
      {
        success: false,
        error: "Error processing donation",
        ...(process.env.NODE_ENV === "development" && {
          details: error.message,
        }),
      },
      { status: 500 }
    );
  }
}
