import nodemailer from "nodemailer";

export async function POST(request) {
  const { email } = await request.json();

  // Create Zoho Mail transporter (using same credentials as before)
  // const transporter = nodemailer.createTransport({
  //   host: process.env.ZOHO_MAIL_HOST,
  //   port: parseInt(process.env.ZOHO_MAIL_PORT),
  //   secure: process.env.ZOHO_MAIL_SECURE === "true",
  //   auth: {
  //     user: process.env.GMAIL_USER}>`, // Use GMAIL_USER for subscriber email,
  //     pass: process.env.ZOHO_MAIL_PASSWORD,
  //   },
  // });

  const transporter = nodemailer.createTransport({
    service: "gmail",
    auth: {
      user: process.env.GMAIL_USER,
      pass: process.env.GMAIL_PASSWORD,
    },
  });

  // Email content for subscriber
  const subscriberMailOptions = {
    from: `ATMA Newsletter <${process.env.GMAIL_USER}>`, // Use GMAIL_USER for subscriber email
    to: email,
    subject: "Thank You for Subscribing to ATMA Newsletter",
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h1 style="color: #1a365d;">Thank You for Subscribing!</h1>
        
        <div style="background-color: #f7fafc; padding: 20px; border-radius: 8px; margin: 20px 0;">
          <p>You've successfully subscribed to the ATMA newsletter. We'll keep you updated with our latest news, events, and updates.</p>
          <p>Your email: <strong>${email}</strong> has been added to our mailing list.</p>
        </div>
        
        <div style="border-top: 1px solid #e2e8f0; padding-top: 20px; font-size: 0.9em; color: #718096;">
          <p>If this was a mistake or you wish to unsubscribe, please contact us at <a href="mailto:Atmausapresident@gmail.com" style="color: #3182ce;">Atmausapresident@gmail.com</a></p>
          <p>© ${new Date().getFullYear()} American Tamil Medical Association. All rights reserved.</p>
        </div>
      </div>
    `,
  };

  // Email content for president
  const presidentMailOptions = {
    from: `ATMA Newsletter <${process.env.GMAIL_USER}>`, // Use GMAIL_USER for subscriber email
    to: "Atmausapresident@gmail.com",
    subject: `New Newsletter Subscriber: ${email}`,
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h1 style="color: #1a365d;">New Newsletter Subscription</h1>
        
        <div style="background-color: #f7fafc; padding: 20px; border-radius: 8px; margin: 20px 0;">
          <p>A new subscriber has joined the ATMA newsletter mailing list:</p>
          <p><strong>Email:</strong> ${email}</p>
          <p><strong>Subscription Date:</strong> ${new Date().toLocaleDateString()}</p>
        </div>
        
        <div style="border-top: 1px solid #e2e8f0; padding-top: 20px; font-size: 0.9em; color: #718096;">
          <p>This email was automatically generated by the ATMA newsletter system.</p>
        </div>
      </div>
    `,
  };

  try {
    // Send both emails
    await transporter.sendMail(subscriberMailOptions);
    await transporter.sendMail(presidentMailOptions);

    return new Response(JSON.stringify({ success: true }), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  } catch (error) {
    console.error("Error sending email via Zoho:", error);
    return new Response(
      JSON.stringify({
        success: false,
        error: error.message,
        stack: process.env.NODE_ENV === "development" ? error.stack : undefined,
      }),
      {
        status: 500,
        headers: { "Content-Type": "application/json" },
      }
    );
  }
}
